' Copyright (c) 2007-2018 Bruce A Henderson
' 
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
' 
' The above copyright notice and this permission notice shall be included in
' all copies or substantial portions of the Software.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
' THE SOFTWARE.
' 
SuperStrict

Import "slikenet/Source/include/*.h"

Import "slikenet/Source/src/Base64Encoder.cpp"
Import "slikenet/Source/src/BitStream.cpp"
Import "slikenet/Source/src/CCRakNetSlidingWindow.cpp"
Import "slikenet/Source/src/CCRakNetUDT.cpp"
Import "slikenet/Source/src/CheckSum.cpp"
Import "slikenet/Source/src/CloudClient.cpp"
Import "slikenet/Source/src/CloudCommon.cpp"
Import "slikenet/Source/src/CloudServer.cpp"
Import "slikenet/Source/src/CommandParserInterface.cpp"
Import "slikenet/Source/src/ConnectionGraph2.cpp"
Import "slikenet/Source/src/ConsoleServer.cpp"
Import "slikenet/Source/src/DataCompressor.cpp"
Import "slikenet/Source/src/DirectoryDeltaTransfer.cpp"
Import "slikenet/Source/src/DR_SHA1.cpp"
Import "slikenet/Source/src/DS_BytePool.cpp"
Import "slikenet/Source/src/DS_ByteQueue.cpp"
Import "slikenet/Source/src/DS_HuffmanEncodingTree.cpp"
Import "slikenet/Source/src/DS_Table.cpp"
Import "slikenet/Source/src/DynDNS.cpp"
Import "slikenet/Source/src/EmailSender.cpp"
Import "slikenet/Source/src/EpochTimeToString.cpp"
Import "slikenet/Source/src/FileList.cpp"
Import "slikenet/Source/src/FileListTransfer.cpp"
Import "slikenet/Source/src/FileOperations.cpp"
Import "slikenet/Source/src/FormatString.cpp"
Import "slikenet/Source/src/FullyConnectedMesh2.cpp"
Import "slikenet/Source/src/Getche.cpp"
Import "slikenet/Source/src/Gets.cpp"
Import "slikenet/Source/src/GetTime.cpp"
Import "slikenet/Source/src/gettimeofday.cpp"
Import "slikenet/Source/src/GridSectorizer.cpp"
Import "slikenet/Source/src/HTTPConnection.cpp"
Import "slikenet/Source/src/HTTPConnection2.cpp"
Import "slikenet/Source/src/IncrementalReadInterface.cpp"
Import "slikenet/Source/src/Itoa.cpp"
Import "slikenet/Source/src/LinuxStrings.cpp"
Import "slikenet/Source/src/linux_adapter.cpp"
Import "slikenet/Source/src/LocklessTypes.cpp"
Import "slikenet/Source/src/LogCommandParser.cpp"
Import "slikenet/Source/src/MessageFilter.cpp"
Import "slikenet/Source/src/NatPunchthroughClient.cpp"
Import "slikenet/Source/src/NatPunchthroughServer.cpp"
Import "slikenet/Source/src/NatTypeDetectionClient.cpp"
Import "slikenet/Source/src/NatTypeDetectionCommon.cpp"
Import "slikenet/Source/src/NatTypeDetectionServer.cpp"
Import "slikenet/Source/src/NetworkIDManager.cpp"
Import "slikenet/Source/src/NetworkIDObject.cpp"
Import "slikenet/Source/src/osx_adapter.cpp"
Import "slikenet/Source/src/PacketConsoleLogger.cpp"
Import "slikenet/Source/src/PacketFileLogger.cpp"
Import "slikenet/Source/src/PacketizedTCP.cpp"
Import "slikenet/Source/src/PacketLogger.cpp"
Import "slikenet/Source/src/PacketOutputWindowLogger.cpp"
Import "slikenet/Source/src/PluginInterface2.cpp"
Import "slikenet/Source/src/PS4Includes.cpp"
Import "slikenet/Source/src/Rackspace.cpp"
Import "slikenet/Source/src/RakMemoryOverride.cpp"
Import "slikenet/Source/src/RakNetCommandParser.cpp"
Import "slikenet/Source/src/RakNetSocket.cpp"
Import "slikenet/Source/src/RakNetSocket2.cpp"
Import "slikenet/Source/src/RakNetSocket2_360_720.cpp"
Import "slikenet/Source/src/RakNetSocket2_Berkley.cpp"
Import "slikenet/Source/src/RakNetSocket2_Berkley_NativeClient.cpp"
Import "slikenet/Source/src/RakNetSocket2_NativeClient.cpp"
Import "slikenet/Source/src/RakNetSocket2_PS3_PS4.cpp"
Import "slikenet/Source/src/RakNetSocket2_PS4.cpp"
Import "slikenet/Source/src/RakNetSocket2_Vita.cpp"
Import "slikenet/Source/src/RakNetSocket2_WindowsStore8.cpp"
Import "slikenet/Source/src/RakNetSocket2_Windows_Linux.cpp"
Import "slikenet/Source/src/RakNetSocket2_Windows_Linux_360.cpp"
Import "slikenet/Source/src/RakNetStatistics.cpp"
Import "slikenet/Source/src/RakNetTransport2.cpp"
Import "slikenet/Source/src/RakNetTypes.cpp"
Import "slikenet/Source/src/RakPeer.cpp"
Import "slikenet/Source/src/RakSleep.cpp"
Import "slikenet/Source/src/RakString.cpp"
Import "slikenet/Source/src/RakThread.cpp"
Import "slikenet/Source/src/RakWString.cpp"
Import "slikenet/Source/src/Rand.cpp"
Import "slikenet/Source/src/RandSync.cpp"
Import "slikenet/Source/src/ReadyEvent.cpp"
Import "slikenet/Source/src/RelayPlugin.cpp"
Import "slikenet/Source/src/ReliabilityLayer.cpp"
Import "slikenet/Source/src/ReplicaManager3.cpp"
Import "slikenet/Source/src/Router2.cpp"
Import "slikenet/Source/src/RPC4Plugin.cpp"
Import "slikenet/Source/src/SecureHandshake.cpp"
Import "slikenet/Source/src/SendToThread.cpp"
Import "slikenet/Source/src/SignaledEvent.cpp"
Import "slikenet/Source/src/SimpleMutex.cpp"
Import "slikenet/Source/src/SocketLayer.cpp"
Import "slikenet/Source/src/StatisticsHistory.cpp"
Import "slikenet/Source/src/StringCompressor.cpp"
Import "slikenet/Source/src/StringTable.cpp"
Import "slikenet/Source/src/SuperFastHash.cpp"
Import "slikenet/Source/src/TableSerializer.cpp"
Import "slikenet/Source/src/TCPInterface.cpp"
Import "slikenet/Source/src/TeamBalancer.cpp"
Import "slikenet/Source/src/TeamManager.cpp"
Import "slikenet/Source/src/TelnetTransport.cpp"
Import "slikenet/Source/src/ThreadsafePacketLogger.cpp"
Import "slikenet/Source/src/TwoWayAuthentication.cpp"
Import "slikenet/Source/src/UDPForwarder.cpp"
Import "slikenet/Source/src/UDPProxyClient.cpp"
Import "slikenet/Source/src/UDPProxyCoordinator.cpp"
Import "slikenet/Source/src/UDPProxyServer.cpp"
Import "slikenet/Source/src/VariableDeltaSerializer.cpp"
Import "slikenet/Source/src/VariableListDeltaTracker.cpp"
Import "slikenet/Source/src/VariadicSQLParser.cpp"
Import "slikenet/Source/src/VitaIncludes.cpp"
Import "slikenet/Source/src/WSAStartupSingleton.cpp"
Import "slikenet/Source/src/_FindFirst.cpp"

Import "glue.cpp"
